### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by JeromeSolis**
Finally managed to translate the Python script into Typescript, Got stuck around data access in Array, embarrassing...
Everything here is net new, but the tsconfig file might be a duplicate. I used this one for my build, but can be discarded

### CODE REVIEW

**Comment by ikesau** [comment]
Hey @JeromeSolis - I'll check this out next weekend. 💪

**Comment by JeromeSolis** [comment]
Amazing, thank you!
Jérôme Solis
C: +1 (514) 945-7722

**Comment by ikesau** [comment]
Hey @JeromeSolis - refactored your TS slightly to be a little easier to work with (using an object literal instead of an array)

Let me know if it looks good to you then we can merge and proceed with the results screen 🙂

**Comment by JeromeSolis** [comment]
I'm good with it. I just realized that it will be merge on master and not webapp though...

**Pull request merged**
